# Generated by Django 3.1.2 on 2022-07-22 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('emblem', models.URLField()),
            ],
            options={
                'db_table': 'league',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('crest', models.URLField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.league')),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='LeagueJapanese',
            fields=[
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.league')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'league_japanese',
            },
        ),
        migrations.CreateModel(
            name='TeamJapanese',
            fields=[
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.team')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'team_japanese',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('match_day', models.PositiveIntegerField()),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='main.team')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='main.team')),
            ],
            options={
                'db_table': 'match',
            },
        ),
    ]
