# Generated by Django 3.1.2 on 2022-07-22 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'season',
            },
        ),
        migrations.AlterField(
            model_name='league',
            name='emblem',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='crest',
            field=models.URLField(null=True),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('name', 'league'), name='unique_team'),
        ),
        migrations.AddField(
            model_name='season',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.league'),
        ),
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.season'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('year', 'league'), name='unique_season'),
        ),
    ]
