# Generated by Django 3.1.2 on 2022-07-21 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueJapanese',
            fields=[
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.league')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'league_japanese',
            },
        ),
    ]
