# Generated by Django 4.1 on 2022-08-30 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="update_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 8, 30, 2, 40, 37, 70577, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="standing",
            name="update_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 8, 30, 2, 40, 37, 71574, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
