# Generated by Django 3.1.2 on 2022-09-07 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_match_update_at_standing_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='update_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='standing',
            name='update_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
