# Generated by Django 3.1.2 on 2022-07-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220722_1123'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('match_day', 'home', 'away', 'season'), name='unique_match'),
        ),
    ]
