# Generated by Django 3.1.2 on 2022-07-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220722_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='code',
            field=models.CharField(default='default', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
