# Generated by Django 3.1.2 on 2022-07-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220722_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='code',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
