# Generated by Django 3.1.2 on 2022-07-26 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220722_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['date']},
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(null=True)),
                ('point', models.PositiveIntegerField()),
                ('played', models.PositiveIntegerField()),
                ('won', models.PositiveIntegerField()),
                ('draw', models.PositiveIntegerField()),
                ('lost', models.PositiveIntegerField()),
                ('goals_for', models.PositiveIntegerField()),
                ('goals_against', models.PositiveIntegerField()),
                ('goals_difference', models.IntegerField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.league')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
            options={
                'db_table': 'standing',
                'ordering': ['rank'],
            },
        ),
        migrations.AddConstraint(
            model_name='standing',
            constraint=models.UniqueConstraint(fields=('team', 'league'), name='unique_standing'),
        ),
    ]
